version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
