# Use the official Node.js image
FROM node:16-alpine
WORKDIR /app
COPY ./frontend/package.json ./frontend/package-lock.json /app/
RUN npm install
COPY ./frontend /app
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
